# Generated by Django 3.0.6 on 2020-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('imdb_rating', models.FloatField()),
                ('cast', models.TextField()),
                ('director', models.CharField(max_length=254)),
                ('movie_type', models.CharField(max_length=254)),
                ('language', models.CharField(default='Hindi', max_length=254)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('torrent_link_1080', models.URLField(blank=True, null=True)),
                ('torrent_link_720', models.URLField(blank=True, null=True)),
                ('direct_link_720', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
