# Generated by Django 3.0.6 on 2020-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
