# Generated by Django 3.0.6 on 2020-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_movielist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='direct_link_720',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='torrent_link_1080',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='torrent_link_720',
            field=models.TextField(blank=True, null=True),
        ),
    ]
