# Generated by Django 3.0.6 on 2020-05-19 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_movielist_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 8, 30, 31, 772618, tzinfo=utc)),
        ),
    ]
