# Generated by Django 3.0.6 on 2020-05-19 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200519_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 8, 32, 15, 834677, tzinfo=utc)),
        ),
    ]
