# Generated by Django 3.0.6 on 2020-05-20 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200520_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='cat',
            field=models.CharField(choices=[('hollywood', 'hollywood'), ('bollywood', 'bollywood'), ('tollywood', 'tollywood'), ('web_series', 'web_series')], default='hollywood', max_length=20),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 13, 48, 47, 872918, tzinfo=utc)),
        ),
    ]
