# Generated by Django 3.0.6 on 2020-05-20 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20200520_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 19, 50, 7, 513586, tzinfo=utc)),
        ),
    ]
