# Generated by Django 3.0.6 on 2020-05-20 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200521_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='title_main',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 19, 54, 49, 634729, tzinfo=utc)),
        ),
    ]
