# Generated by Django 3.0.6 on 2020-05-20 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20200521_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 21, 3, 40, 448435, tzinfo=utc)),
        ),
    ]
